{
 "title": "Bitcoin",
 "time": { "from": "2016-12-31T23:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Bitcoin",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "query": "from(bucket: \"bitcoin\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bitcoin\")\n  |> filter(fn: (r) => r[\"_field\"] == \"balance\")\n  |> filter(fn: (r) => r[\"type\"] == \"hourly\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"wallet\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r[\"Bitcoin S\"] + r[\"Bitcoin X\"] + r[\"multisig_2_of_3_ledger_1\"]}))\n  |> drop(columns: [\"Bitcoin S\", \"Bitcoin X\", \"multisig_2_of_3_ledger_1\"])\n  |> toFloat()\n  |> map(fn: (r) => ({ r with _value: r._value / 100000000.0}))\n\n"
    }
   ]
  },
  {
   "title": "Wallets",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "query": "from(bucket: \"bitcoin\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bitcoin\")\n  |> filter(fn: (r) => r[\"_field\"] == \"balance\")\n  |> filter(fn: (r) => r[\"type\"] == \"hourly\")\n  |> group(columns: [\"_field\", \"_measurement\", \"wallet\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> toFloat()\n  |> map(fn: (r) => ({ r with _value: r._value / 100000000.0}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "USD and CHF",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "sats = from(bucket: \"bitcoin\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bitcoin\")\n  |> filter(fn: (r) => r[\"_field\"] == \"balance\")\n  |> filter(fn: (r) => r[\"type\"] == \"hourly\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"wallet\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r[\"Bitcoin S\"] + r[\"Bitcoin X\"] + r[\"multisig_2_of_3_ledger_1\"]}))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> set(key: \"what\", value: \"sats\")\n  |> toFloat()\n\nbtc_price_usd = from(bucket: \"bitcoin\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bitcoin\")\n  |> filter(fn: (r) => r[\"_field\"] == \"btc_price_usd\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> set(key: \"what\", value: \"btc_price_usd\")\n\n\nunion(tables: [sats, btc_price_usd])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"what\"], valueColumn: \"_value\")\n|> map(fn: (r) => ({ r with USD: r[\"sats\"] * r[\"btc_price_usd\"] / 100000000.0}))\n|> keep(columns: [\"_time\", \"USD\"])\n|> filter(fn: (r) => r.USD >= 0)"
    },
    {
     "query": "sats = from(bucket: \"bitcoin\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bitcoin\")\n  |> filter(fn: (r) => r[\"_field\"] == \"balance\")\n  |> filter(fn: (r) => r[\"type\"] == \"hourly\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"wallet\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r[\"Bitcoin S\"] + r[\"Bitcoin X\"] + r[\"multisig_2_of_3_ledger_1\"]}))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> set(key: \"what\", value: \"sats\")\n  |> toFloat()\n\nbtc_price_usd = from(bucket: \"bitcoin\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bitcoin\")\n  |> filter(fn: (r) => r[\"_field\"] == \"btc_price_usd\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> set(key: \"what\", value: \"btc_price_usd\")\n\nusd_chf = from(bucket: \"bitcoin\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bitcoin\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usd_chf\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> set(key: \"what\", value: \"usd_chf\")\n\n\nunion(tables: [sats, btc_price_usd, usd_chf])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"what\"], valueColumn: \"_value\")\n|> map(fn: (r) => ({ r with CHF: r[\"sats\"] * r[\"btc_price_usd\"] / 100000000.0 * r[\"usd_chf\"]}))\n|> keep(columns: [\"_time\", \"CHF\"])\n|> filter(fn: (r) => r.CHF >= 0)"
    }
   ]
  },
  {
   "title": "BTC price",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"bitcoin\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bitcoin\")\n  |> filter(fn: (r) => r[\"_field\"] == \"btc_price_usd\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "USD to CHF",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "targets": [
    {
     "query": "from(bucket: \"bitcoin\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bitcoin\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usd_chf\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}